// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMCfwwY5S1t-f7l0TXVT2aTPKuGfd4LLM',
    appId: '1:688465903436:web:f11471c2bbd95d78a9d9e9',
    messagingSenderId: '688465903436',
    projectId: 'cotiznow-a609d',
    authDomain: 'cotiznow-a609d.firebaseapp.com',
    storageBucket: 'cotiznow-a609d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLuBRtfAiFraO3SRUWwIE2KoPBNZHy1ik',
    appId: '1:688465903436:android:67cb10ce94b73724a9d9e9',
    messagingSenderId: '688465903436',
    projectId: 'cotiznow-a609d',
    storageBucket: 'cotiznow-a609d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxfdwb1MRWxN3n4IQ9F2RkWFwHKweYdrk',
    appId: '1:688465903436:ios:b66132ecf04fe3e6a9d9e9',
    messagingSenderId: '688465903436',
    projectId: 'cotiznow-a609d',
    storageBucket: 'cotiznow-a609d.appspot.com',
    iosBundleId: 'com.example.cotiznow',
  );
}
